# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '13.5'

  # Pods for iosApp
  pod 'MultiPlatformLibraryMvvm', :git => 'https://github.com/icerockdev/moko-mvvm.git', :tag => 'release/0.9.1'

  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iosAppUITests' do
    # Pods for testing
  end

end
